name: Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./SzamlazzHuTest
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./SzamlazzHuTest
    - name: Test
      env:
        SZAMLAZZ_HU_KEY: ${{ secrets.SZAMLAZZ_HU_KEY }}
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
      working-directory: ./SzamlazzHuTest
    - name: Coveralls Upload
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: SzamlazzHuTest/coverage.info
